//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Akifev_Nikita_Aleksandrovich.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int Id_matches { get; set; }
        public Nullable<int> Id_turnir { get; set; }
        public Nullable<int> Id_player { get; set; }
        public Nullable<System.DateTime> Date_Begin_matches { get; set; }
        public string result_matches { get; set; }
        public string time_matches { get; set; }
        public string NameCommand { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Turnirs Turnirs { get; set; }
    }
}
