//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Akifev_Nikita_Aleksandrovich.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentDBEntities : DbContext
    {
        public TournamentDBEntities()
            : base("name=TournamentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Level_dostupa> Level_dostupa { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Organizator> Organizator { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Status_turnir> Status_turnir { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Turnir_tables> Turnir_tables { get; set; }
        public virtual DbSet<Turnirs> Turnirs { get; set; }
    }
}
