//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Akifev_Nikita_Aleksandrovich.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnir_tables
    {
        public int Id_Turnir_tables { get; set; }
        public Nullable<int> Id_turnir { get; set; }
        public Nullable<int> Id_player { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> kol_vo_win { get; set; }
        public Nullable<int> kol_vo_lose { get; set; }
        public string Mesto_v_table { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Turnirs Turnirs { get; set; }
    }
}
